spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog02
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout:
      seconds: 900
    store-type: jdbc
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true